import { Inter } from "next/font/google";
import "./globals.css";
import "@/styles/style.css";
import "@/styles/blue.css";
import "@/styles/theme.css";
import { ThemeSwith } from "@/Components/ThemeSwitch/ThemeSwith";
import Sidebar from "@/Components/Sidebar/Sidebar";
import ThemeProviders from "@/Providers/ThemeProvider/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviders >
          <ThemeSwith />
          <Sidebar />
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
